/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Data regarding a line consisting of tracks.
 */
export interface RailLine {
  /**
   * Unique identifier for this line. Must not include: ':'!
   */
  id: string;
  /**
   * Version identifier for the line. Any changes in the track data imply a change in the version. Must not include: ':'!
   */
  version: string;
  /**
   * [Optional] Human readable name of this line.
   */
  name?: string;
  /**
   * List of tracks of this line.
   *
   * @minItems 1
   */
  tracks: [
    {
      /**
       * Unique identifier for this track. Must not include: ':'!
       */
      id: string;
      /**
       * GeoJSON geometry of the track
       */
      data: {
        /**
         * Fixed GeoJSON type.
         */
        type: "LineString";
        /**
         * @minItems 1
         */
        coordinates: [[number, number], ...[number, number][]];
      };
      /**
       * [Optional] Human readable name of this track.
       */
      name?: string;
      /**
       * [Optional] Marker of different type to be displayed on the track.
       */
      markers?: {
        /**
         * List of marker types used in the data.
         *
         * @minItems 1
         */
        types: [
          {
            /**
             * Unique identifier for this type.
             */
            id: string;
            /**
             * Human readable name of this type.
             */
            name: string;
            /**
             * [Optional] Description of this marker type.
             */
            description?: string;
          },
          ...{
            /**
             * Unique identifier for this type.
             */
            id: string;
            /**
             * Human readable name of this type.
             */
            name: string;
            /**
             * [Optional] Description of this marker type.
             */
            description?: string;
          }[]
        ];
        /**
         * List of markers.
         *
         * @minItems 1
         */
        data: [
          {
            /**
             * Unique identifier for this marker.
             */
            id: string;
            /**
             * Human readable name of this marker.
             */
            name: string;
            /**
             * Type of this marker. Must match one of the defined marker types.
             */
            type: string;
            /**
             * GeoJSON point for this marker.
             */
            position: {
              /**
               * Fixed GeoJSON type.
               */
              type: "Point";
              /**
               * @minItems 2
               * @maxItems 2
               */
              coordinates: [number, number];
            };
            /**
             * [Optional] Description of this marker.
             */
            description?: string;
            /**
             * [Optional] Additional structured information without schema restrictions.
             */
            extra?: {
              [k: string]: unknown;
            };
          },
          ...{
            /**
             * Unique identifier for this marker.
             */
            id: string;
            /**
             * Human readable name of this marker.
             */
            name: string;
            /**
             * Type of this marker. Must match one of the defined marker types.
             */
            type: string;
            /**
             * GeoJSON point for this marker.
             */
            position: {
              /**
               * Fixed GeoJSON type.
               */
              type: "Point";
              /**
               * @minItems 2
               * @maxItems 2
               */
              coordinates: [number, number];
            };
            /**
             * [Optional] Description of this marker.
             */
            description?: string;
            /**
             * [Optional] Additional structured information without schema restrictions.
             */
            extra?: {
              [k: string]: unknown;
            };
          }[]
        ];
      };
    },
    ...{
      /**
       * Unique identifier for this track. Must not include: ':'!
       */
      id: string;
      /**
       * GeoJSON geometry of the track
       */
      data: {
        /**
         * Fixed GeoJSON type.
         */
        type: "LineString";
        /**
         * @minItems 1
         */
        coordinates: [[number, number], ...[number, number][]];
      };
      /**
       * [Optional] Human readable name of this track.
       */
      name?: string;
      /**
       * [Optional] Marker of different type to be displayed on the track.
       */
      markers?: {
        /**
         * List of marker types used in the data.
         *
         * @minItems 1
         */
        types: [
          {
            /**
             * Unique identifier for this type.
             */
            id: string;
            /**
             * Human readable name of this type.
             */
            name: string;
            /**
             * [Optional] Description of this marker type.
             */
            description?: string;
          },
          ...{
            /**
             * Unique identifier for this type.
             */
            id: string;
            /**
             * Human readable name of this type.
             */
            name: string;
            /**
             * [Optional] Description of this marker type.
             */
            description?: string;
          }[]
        ];
        /**
         * List of markers.
         *
         * @minItems 1
         */
        data: [
          {
            /**
             * Unique identifier for this marker.
             */
            id: string;
            /**
             * Human readable name of this marker.
             */
            name: string;
            /**
             * Type of this marker. Must match one of the defined marker types.
             */
            type: string;
            /**
             * GeoJSON point for this marker.
             */
            position: {
              /**
               * Fixed GeoJSON type.
               */
              type: "Point";
              /**
               * @minItems 2
               * @maxItems 2
               */
              coordinates: [number, number];
            };
            /**
             * [Optional] Description of this marker.
             */
            description?: string;
            /**
             * [Optional] Additional structured information without schema restrictions.
             */
            extra?: {
              [k: string]: unknown;
            };
          },
          ...{
            /**
             * Unique identifier for this marker.
             */
            id: string;
            /**
             * Human readable name of this marker.
             */
            name: string;
            /**
             * Type of this marker. Must match one of the defined marker types.
             */
            type: string;
            /**
             * GeoJSON point for this marker.
             */
            position: {
              /**
               * Fixed GeoJSON type.
               */
              type: "Point";
              /**
               * @minItems 2
               * @maxItems 2
               */
              coordinates: [number, number];
            };
            /**
             * [Optional] Description of this marker.
             */
            description?: string;
            /**
             * [Optional] Additional structured information without schema restrictions.
             */
            extra?: {
              [k: string]: unknown;
            };
          }[]
        ];
      };
    }[]
  ];
  /**
   * Information and configuration for map representations.
   */
  map: {
    /**
     * [Optional] Starting configuration for a map view.
     */
    startConfiguration?: {
      /**
       * Latitude in degrees.
       */
      latitude: number;
      /**
       * Longitude in degrees.
       */
      longitude: number;
      /**
       * [Optional] Heading in degrees.
       */
      zoom?: number;
    };
  };
}
